In [1]:
from google.colab import drive
drive.mount('/content/drive',  force_remount=True)

Mounted at /content/drive


In [2]:
import sys
sys.path.append('/content/drive/MyDrive/thesis')
import script

In [3]:
print(script.hello_world())

Hello, World!
None


In [1]:
import torch
import numpy as np

In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data.type

<function Tensor.type>

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3101, 0.1373],
        [0.2667, 0.1460]]) 



In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8327, 0.4011, 0.2837],
        [0.3190, 0.0632, 0.5379]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"The type of the object is: {torch.typename(tensor)}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
The type of the object is: torch.FloatTensor


In [10]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
print(torch.cuda.get_device_name(0))

Tesla T4


In [11]:
tensor = torch.rand(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[:, -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([0.0703, 0.7521, 0.7686, 0.6433])
First column:  tensor([0.0703, 0.2114, 0.1024, 0.1642])
Last column: tensor([0.6433, 0.2339, 0.5317, 0.3559])
tensor([[0.0703, 0.0000, 0.7686, 0.6433],
        [0.2114, 0.0000, 0.3738, 0.2339],
        [0.1024, 0.0000, 0.1199, 0.5317],
        [0.1642, 0.0000, 0.4388, 0.3559]])


In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[0.0703, 0.0000, 0.7686, 0.6433],
        [0.2114, 0.0000, 0.3738, 0.2339],
        [0.1024, 0.0000, 0.1199, 0.5317],
        [0.1642, 0.0000, 0.4388, 0.3559],
        [0.0703, 0.0000, 0.7686, 0.6433],
        [0.2114, 0.0000, 0.3738, 0.2339],
        [0.1024, 0.0000, 0.1199, 0.5317],
        [0.1642, 0.0000, 0.4388, 0.3559],
        [0.0703, 0.0000, 0.7686, 0.6433],
        [0.2114, 0.0000, 0.3738, 0.2339],
        [0.1024, 0.0000, 0.1199, 0.5317],
        [0.1642, 0.0000, 0.4388, 0.3559]])


In [13]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.0049, 0.0000, 0.5907, 0.4138],
        [0.0447, 0.0000, 0.1397, 0.0547],
        [0.0105, 0.0000, 0.0144, 0.2827],
        [0.0270, 0.0000, 0.1925, 0.1267]])

In [14]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

4.014121055603027 <class 'float'>


In [15]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.0703, 0.0000, 0.7686, 0.6433],
        [0.2114, 0.0000, 0.3738, 0.2339],
        [0.1024, 0.0000, 0.1199, 0.5317],
        [0.1642, 0.0000, 0.4388, 0.3559]]) 

tensor([[5.0703, 5.0000, 5.7686, 5.6433],
        [5.2114, 5.0000, 5.3738, 5.2339],
        [5.1024, 5.0000, 5.1199, 5.5317],
        [5.1642, 5.0000, 5.4388, 5.3559]])


In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [21]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [22]:
n = np.ones(5)
t = torch.from_numpy(n)

In [23]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
