In [2]:
import torch

In [3]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [4]:
print(w)
print(x)
print(z)
print(loss)

tensor([[ 0.2732,  0.7941, -0.2988],
        [-0.7693, -0.7938, -1.0638],
        [-0.0212,  0.1957,  1.4420],
        [-2.4149, -0.8668, -2.0740],
        [-1.6119, -0.9721,  0.4469]], requires_grad=True)
tensor([1., 1., 1., 1., 1.])
tensor([-4.4704, -2.3054, -0.6679], grad_fn=<AddBackward0>)
tensor(0.1735, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [5]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7a4eb96dc040>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7a4eb985bca0>


In [6]:
print(w.grad)
print(b.grad)

None
None


In [7]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0038, 0.0302, 0.1130],
        [0.0038, 0.0302, 0.1130],
        [0.0038, 0.0302, 0.1130],
        [0.0038, 0.0302, 0.1130],
        [0.0038, 0.0302, 0.1130]])
tensor([0.0038, 0.0302, 0.1130])


In [8]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [9]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False
